SELECT
id,
CreatedDate,
toLabel(Disqualified_Reasons__c), 
Entered_Disqualified_Date__c, 
howDidYouHearAboutUs__c, 
How_Did_You_Hear_About_Us_Reasons__c,
toLabel(Nurture_Reasons__c),
Entered_Nurture_Date__c,
Status,
Disqualified_Other__c,
Nurture_Other__c,
type__c,
Owner.name,
Job_Function__c, 
Job_Level__c,
UserGems__Is_a_UserGem__c,
LD_BookIt_Log_ID__c,
Account_Segment__c,
UTM_Campaign__c,
Original_UTM_Campaign__c, 
UTM_Source__c,
Original_UTM_Source__c, 
UTM_Medium__c, 
Original_UTM_Medium__c, 
UTM_Content__c, 
Original_UTM_Content__c, 
UTM_Description__c, 
Original_UTM_Description__c,
Campaign_Type__c,
FirstName,
LastName,
Email,
Date_of_First_Activity__c, 
LastActivityDate,
Last_Inbound_Email_Sent__c,
Last_Outbound_Email_Sent__c,
No_Longer_at_Company__c,
Left_or_inactive__c,
HasOptedOutOfEmail,
OutReach_OptOut__c

FROM Lead
WHERE (type__c != 'Job Seeker' OR type__c = NULL)
AND ConvertedContact.Id = NULL
