
version: 2

models:
  - name: ob_tactical_metrics
    description: "Tactical metrics for Outbound"
    columns:
      - name: first_activity_date
        description: "Account's first activity date"
    
      - name: account_latest_MQL_date
        description: "Accounts latest MQL date"

      - name: latest_mql_contact_id
        description: "Contact ID of the latest MQL"

      - name: owner_name
        description: "Account's owner name"

      - name: job_scraping_date
        description: "Date of the job scraping"

      - name: no_open_tech_roles
        description: "Number of open tech roles"

      - name: account_name
        description: "Account name"

      - name: SQO
        description: "Sales Qualified Opportunity"

      - name: Closed_Won
        description: "Closed Won"

      - name: SAL
        description: "Sales Accepted Lead"

      - name: SAL_name
        description: "Sales Accepted Lead name"

      - name: sqo_date
        description: "SQO date"

      - name: closed_won_date
        description: "Closed Won date"

      - name: sal_date
        description: "SAL date"

      - name: access
        description: "Access"

      - name: access_date
        description: "Access date"

      - name: related_contact_id

      - name: activity_date
        description: "Activity date"

      - name: activity_owner

      - name: first_activity_owner

      - name: activity_subject

      - name: call_duration

      - name: event_type

      - name: contact_last_mql_date
        description: "Contact's last MQL date"

      - name: job_function

      - name: job_level

      - name: contact_disqualified_reason

      - name: disqualified_date

      - name: disqualified_open_field

      - name: nurture_reason

      - name: nurture_date

      - name: nurture_open_field

      - name: contact_status

      - name: related_contact_name

      - name: is_usergem

      - name: account_segment

      - name: tech_vs_nontech

      - name: most_recent_ivr

      - name: most_recent_position_posted

      - name: account_status

      - name: m_access


      - name: m_access_link

      - name: m_account_link

      - name: m_account_link_classic

      - name: m_bucket

      - name: m_call_duration

      - name: m_contact_id

      - name: m_contact_link

      - name: m_cw_link

      - name: m_cws

      - name: m_first_activity_date_business_days

      - name: m_ivr

      - name: m_manager

      - name: m_mql_contact_link

      - name: m_position_posted

      - name: m_sal

      - name: m_sal_link

      - name: m_sal_link_classic

      - name: m_sqo

      - name: m_sqo_link

      - name: m_task_before_sal

      - name: m_weekday_first_activity

      - name: account_status_1

  - name: engagement_events
    description: "Engagement events from Hired Salesforce data"
    columns:
      - name: event_date
        description: "Event date"

      - name: event_type
        description: "Event type"

      - name: event_attribute
        description: "Event attribute"

      - name: event_attribute_2
        description: "Event attribute 2"

      - name: event_attribute_3
        description: "Event attribute 3"

      - name: event_attribute_4
        description: "Event attribute 4"

      - name: event_id
        description: "Event ID"

      - name: last_event_date
        description: "Last event date"

      - name: last_event_type
        description: "Last event type"

      - name: event_number
        description: "Event number"

      - name: days_since_last_event
        description: "Days since last event"

      - name: total_events
        description: "Total events"

      - name: date
        description: "Date"

      - name: lead_id
        description: "Lead ID"

      - name: account_id
        description: "Account ID"

      - name: coalesced_id
        description: "Coalesced ID"


