name: Run Data Pipelines in GBQ
on:
    schedule:
        # run every hour from 4 am to 6 pm from monday to friday
        - cron: '0 4-18 * * 1-5'
jobs:
    run-pipeline:
        name: Run Pipeline
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
            packages: read
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.10
              uses: actions/setup-python@v4
              with:
                python-version: "3.10"
            - name: Install dependencies
              run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
            - name: Google Auth
              id: auth
              uses: google-github-actions/auth@v1.1.1
              with:
                workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
                service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
                create_credentials_file: true
                access_token_lifetime: '300s'

            - name: Set up gcloud Cloud SDK environment
              uses: google-github-actions/setup-gcloud@v1.1.1

            - name: 'gcloud test'
              run: |-
                gcloud services list

            - name: Run pipeline
              env: 
                SF_USER: ${{ secrets.SF_USER }}
                SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
                SF_TOKEN: ${{ secrets.SF_TOKEN }}
              run: |
                    python src/salesforce.py


          # add a new step for dbt

            - name: 'dbt test'
              working-directory: ./fast_dw
              env:
                    PROJECT_ID: ${{ secrets.PROJECT_ID }}
                    # get current directory
                    DBT_PROFILES_DIR:  ${{ github.workspace }}/fast_dw
                    DBT_PROJECT_DIR: ${{ github.workspace }}/fast_dw
                    DBT_TOKEN : ${{ steps.auth.outputs.access_token }}
              run: |-
                    dbt --log-level debug build --target dev --full-refresh --no-version-check