
name: DBT Build Test
on:
    push:
        branches:
            - main

jobs:
    run-pipeline:
        name: DBT Build Test
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
            packages: read
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.10
              uses: actions/setup-python@v4
              with:
                python-version: "3.10"
            - name: Install dependencies
              run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
            - name: Google Auth
              id: auth
              uses: google-github-actions/auth@v1.1.1
              with:
                workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
                service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
                create_credentials_file: true
                access_token_lifetime: '300s'

            - name: Authenticate using service account
              working-directory: ./fast_dw
              run: 'echo "$KEYFILE" > ./dbt-service-account.json'
              shell: bash
              env:
                KEYFILE: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
            - name: 'dbt test'
              working-directory: ./fast_dw
              env:
                    GOOGLE_APPLICATION_CREDENTIALS: ./dbt-service-account.json
                    DBT_PROFILES_DIR: ./
                    DBT_PROJECT_DIR: ./
              run: |-
                    ls
                    echo $GOOGLE_APPLICATION_CREDENTIALS
                    
                    dbt deps --target dev
                    dbt build --target dev --full-refresh --no-version-check


