
name: DBT Build Test
on:
    push:
        branches:
            - main

jobs:
    run-pipeline:
        name: DBT Build Test
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
            packages: read
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.10
              uses: actions/setup-python@v4
              with:
                python-version: "3.10"
            - name: Install dependencies
              run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
            - name: Google Auth
              id: auth
              uses: google-github-actions/auth@v1.1.1
              with:
                workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
                service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
                create_credentials_file: true
                access_token_lifetime: '300s'

            - name: Set up gcloud Cloud SDK environment
              uses: google-github-actions/setup-gcloud@v1.1.1
  
            - name: 'gcloud test'
              run: |-
                  gcloud services list
                
            - name: 'dbt test'
              working-directory: ./fast_dw
              env:
                    PROJECT_ID: ${{ secrets.PROJECT_ID }}
                    # get current directory
                    DBT_PROFILES_DIR:  ${{ github.workspace }}/fast_dw
                    DBT_PROJECT_DIR: ${{ github.workspace }}/fast_dw
              run: |-
                    dbt --log-level debug build --target dev --full-refresh --no-version-check


